/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.admin.auth.login": [],
    "filament.admin.auth.logout": [],
    "filament.admin.pages.dashboard": [],
    "filament.admin.resources.articles.index": [],
    "filament.admin.resources.articles.create": [],
    "filament.admin.resources.articles.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.articles.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.consultations.index": [],
    "filament.admin.resources.consultations.create": [],
    "filament.admin.resources.consultations.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.journals.index": [],
    "filament.admin.resources.journals.create": [],
    "filament.admin.resources.journals.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.moods.index": [],
    "filament.admin.resources.moods.create": [],
    "filament.admin.resources.moods.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.psychologists.index": [],
    "filament.admin.resources.users.index": [],
    "filament.admin.resources.users.create": [],
    "filament.admin.resources.users.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "sanctum.csrf-cookie": [],
    "default.livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "google.redirect": [],
    "google.callback": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "moods.store": [],
    "journals.index": [],
    "journals.store": [],
    "journals.update": [
        {
            "name": "journal",
            "required": true,
            "binding": "id"
        }
    ],
    "journals.destroy": [
        {
            "name": "journal",
            "required": true,
            "binding": "id"
        }
    ],
    "mahasiswa.dashboard": [],
    "mahasiswa.chat.index": [],
    "mahasiswa.chat.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "mahasiswa.chat.message": [
        {
            "name": "id",
            "required": true
        }
    ],
    "mahasiswa.consultation.store": [],
    "mahasiswa.forum.index": [],
    "mahasiswa.forum.create": [],
    "mahasiswa.forum.store": [],
    "mahasiswa.forum.reply": [
        {
            "name": "id",
            "required": true
        }
    ],
    "mahasiswa.journal.index": [],
    "mahasiswa.journal.create": [],
    "mahasiswa.journal.show": [
        {
            "name": "journal",
            "required": true,
            "binding": "id"
        }
    ],
    "mahasiswa.articles.index": [],
    "mahasiswa.articles.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "mahasiswa.notifications.index": [],
    "mahasiswa.notifications.readAll": [],
    "psikolog.dashboard": [],
    "psikolog.chat.index": [],
    "psikolog.chat.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "psikolog.chat.message": [
        {
            "name": "id",
            "required": true
        }
    ],
    "psikolog.schedule": [],
    "psikolog.schedule.update": [],
    "psikolog.consultations": [],
    "psikolog.consultations.accept": [
        {
            "name": "id",
            "required": true
        }
    ],
    "psikolog.consultations.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "psikolog.students.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "psikolog.export": [],
    "psikolog.export.download": [],
    "psikolog.articles": [],
    "psikolog.articles.store": [],
    "psikolog.articles.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "psikolog.articles.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
